Add `--tree` option to `dds ls`
ScilifelabDataCentre/dds_cli pull request #136
Opened 2021-08-13 10:17 UTC by ErikDanielsson

Added `--tree` option to `dds ls` for showing the whole file tree in the remote. Should close #111. Showing file sizes depends on merging https://github.com/ScilifelabDataCentre/dds_web/pull/547.

### Note about implementation
The method uses two tree walks, one for constructing the file tree and computing the maximum indentation needed, and one for the construction of the `rich` tree construction. These could however be coalesced into one by updating the subtrees recursively if one finds that the maximum indentation needed for one subtree is greater than the other subtrees. I didn't implement it this way for readability (and ease of implementation) reasons. If it happens that this command is slow with the current implementation however, the improved speed of using one tree walk could perhaps justify the added complexity.

2021-08-13 12:04 UTC, ErikDanielsson commented on dds_cli/data_lister.py
> +            # Rich outputs precisely one line per
```suggestion
            # Rich outputs precisely one line per file/folder
```

2021-08-16 08:51 UTC, inaod568 commented on dds_cli/data_lister.py
> +            subtrees: list[Union["FileTree", Tuple[str, str]]] = None
I get the following traceback
```
  File "/Users/inaod568/repos/DDS/dds_cli/dds_cli/__main__.py", line 312, in ls
    lister.list_recursive(show_size=size)
  File "/Users/inaod568/repos/DDS/dds_cli/dds_cli/data_lister.py", line 325, in list_recursive
    class FileTree:
  File "/Users/inaod568/repos/DDS/dds_cli/dds_cli/data_lister.py", line 330, in FileTree
    subtrees: list[Union["FileTree", Tuple[str, str]]] = None
TypeError: 'type' object is not subscriptable
```

2021-08-16 09:00 UTC, inaod568 requested changes

2021-08-16 09:07 UTC, ErikDanielsson commented on dds_cli/data_lister.py
> +            subtrees: list[Union["FileTree", Tuple[str, str]]] = None
Didn't know this, thanks! Weird that it executed correctly on my machine.

2021-08-16 09:09 UTC, inaod568 approved these changes
Looks good, I like it!

2021-08-16 09:10 UTC, inaod568 commented on dds_cli/data_lister.py
> +            subtrees: list[Union["FileTree", Tuple[str, str]]] = None
Yeah, I'm not sure why it's behaving differently!

2021-08-16 09:10 UTC, merged