Possible to trigger TOTP activation and login using TOTP
ScilifelabDataCentre/dds_cli pull request #259
Opened 2022-02-24 18:20 UTC by alneberg

Before submitting a pr:
- [x] Tests passing
- [x] Black formatting
- [x] Rebase/merge the `dev` branch
- [ ] Note in the CHANGELOG

2022-04-21 07:11 UTC, inaod568 requested changes

2022-04-21 09:12 UTC, aanil commented on dds_cli/user.py
> +                    raise exceptions.ApiRequestError(message=str(err)) from err
There's an extra try again step here thats not in the `request_get()` func
`try_again = rich.prompt.Confirm.ask(
                            "Second factor authentication failed, would you like to try again?"`

2022-05-05 07:15 UTC, inaod568 reviewed
Seems to be a bug somewhere. The one-time code is never accepted.
```
root@a119c8420857:/code# dds auth twofactor
     ︵ 
 ︵ (  )   ︵ 
(  ) ) (  (  )   SciLifeLab Data Delivery System 
 ︶  (  ) ) (    http://dds_backend:5000/ 
      ︶ (  )    Version 1.0.3 
          ︶
INFO     Starting configuration of one-time authentication code method.                                         
? Which method would you like to use? Authenticator App
INFO     No saved token found, or token has expired, proceeding with authentication                             
DDS username: unituser_1
DDS password: 
INFO     Please enter the one-time authentication code sent to your email address (leave empty to exit):        
Authentication one-time code: 14367889
Authentication one-time code: 14367889
Authentication one-time code: 
```

2022-05-05 07:20 UTC, inaod568 commented
@alneberg @aanil Also, all requests now go through the `perform_request` function in the `utils.py` module

2022-05-05 07:27 UTC, alneberg commented
Yes, the bug seems to be due to an indentation misstake in the merge with dev. Should be easy to fix.

2022-05-12 05:45 UTC, inaod568 commented
@alneberg @aanil You can add the following to a `codecov.yml` file in the repo root, this is the same as we have in the `dds_web`
```
coverage:
  status:
    project:
      default:
        threshold: 5%
    patch: off
```

2022-05-12 05:50 UTC, inaod568 commented
@zishanmirza commented the following in the Slack `dds-development` channel:

> I noticed the cli doesn't have tests for TOTP. Would be great to add that to the PR.

2022-05-12 07:05 UTC, inaod568 requested changes
Works well! If you could add a couple of tests though, that would be great! You don't have to add heaps, but look at the existing tests regarding `perform_request` and a couple new ones for this.

2022-05-13 05:55 UTC, inaod568 commented on CHANGELOG.md
> +- Pin versions in `requirements-dev.txt`: New version of `sphinx-click` makes `:nested: full` not work anymore (direct commit: <https://github.com/ScilifelabDataCentre/dds_cli/commit/b91332b43e9cdee4
```suggestion
- Pin versions in `requirements-dev.txt`: New version of `sphinx-click` makes `:nested: full` not work anymore (direct commit: https://github.com/ScilifelabDataCentre/dds_cli/commit/b91332b43e9cdee40a8132eab15e2fea3201bab6)
```

2022-05-13 06:08 UTC, inaod568 approved these changes
Looks great here too!

2022-05-13 06:09 UTC, merged