Project Access Fix Message
ScilifelabDataCentre/dds_cli pull request #446
Opened 2022-03-30 15:07 UTC by zishanmirza

This patch adds a message when the project access would be fixed for a user.

Before submitting a PR to the `dev` branch:
- [X] Tests passing
- [X] Black formatting
- [X] Rebase/merge the `dev` branch
- [ ] Note in the CHANGELOG

2022-04-01 09:47 UTC, inaod568 requested changes

2022-04-01 09:47 UTC, inaod568 commented on dds_cli/account_manager.py
> +                )
Seems like the issue is only that the `msg` on line 374 is not printed out, so I suggest that we remove this and instead we add `dds_cli.utils.console.print(msg)` on line 381, outside of the if / else
```suggestion
```

2022-04-05 12:20 UTC, zishanmirza commented
I have removed the `if` statement and added `dds_cli.utils.console.print(msg)`.

2022-04-05 12:21 UTC, zishanmirza commented
I have removed the `if` statement and added `dds_cli.utils.console.print(msg)`.

2022-04-05 12:51 UTC, inaod568 commented on CHANGELOG.md
> +- Add a message when the project access would be fixed for a user. ([#446](https://github.com/ScilifelabDataCentre/dds_cli/pull/446))
```suggestion
- Patch: Add a message when the project access would be fixed for a user. ([#446](https://github.com/ScilifelabDataCentre/dds_cli/pull/446))
```

2022-04-05 12:52 UTC, inaod568 approved these changes

2022-04-05 12:52 UTC, merged