Replace "requests.get" with the "request_get" function
ScilifelabDataCentre/dds_cli pull request #463
Opened 2022-04-20 13:10 UTC by zishanmirza

This patch replaces "requests.get" with the "request_get" function in "utils.py".

Fixes DDS-1236.

Before submitting a PR to the `dev` branch:
- [X] Tests passing
- [X] Black formatting
- [X] Rebase/merge the `dev` branch
- [ - ] Note in the CHANGELOG

2022-04-21 05:15 UTC, inaod568 requested changes
Change in function name and also need to refactor the end of the function: https://github.com/ScilifelabDataCentre/dds_cli/pull/463/files#diff-51fea701513da58b2a0a4b204b195162b68d9f5f57e782277cc4365d4944a0f6R155-R175

```
if not response.ok:
```
etc is already checked by `request_get` and what's returned by the function is already in json.

2022-04-21 05:15 UTC, inaod568 commented on dds_cli/base.py
> +        response = utils.request_get.get(
```suggestion
        response = utils.request_get(
```

2022-04-21 06:13 UTC, valyo commented on dds_cli/base.py
>          if not response.ok:
this is handled inside the request_get and will fail here

2022-04-21 06:16 UTC, valyo commented on dds_cli/base.py
>          if not response.ok:
this is handled inside the request_get and will fail here

2022-04-21 06:24 UTC, valyo commented on dds_cli/base.py
>          if not response.ok:
the response check and getting the json are handled inside the request_get and will fail here anyways

2022-04-21 11:08 UTC, inaod568 requested changes

2022-04-21 11:08 UTC, inaod568 commented on dds_cli/base.py
>              utils.console.print(
I just realised that the string here is missing an `f` before `"` so `{key_type}` will always be printed out in this case and not the actual value. Can you change that too please while you're at it?

2022-04-21 11:22 UTC, inaod568 requested changes

2022-04-21 11:22 UTC, inaod568 commented on dds_cli/base.py
> +            error_message="Failed to get cloud information: The database seems to be down.",
": The database seems to be down." is defined in the `request_get` function. Also, this old message is a bit confusing and a bit misrepresenting, so change that row to this: 
```suggestion
            error_message="Failed to project key",
```

2022-04-21 11:52 UTC, inaod568 commented on dds_cli/base.py
> +            error_message="Failed to get project key.",
```suggestion
            error_message="Failed to get project key",
```

2022-04-22 06:55 UTC, inaod568 commented on dds_cli/base.py
>              utils.console.print(
@zishanmirza

2022-04-22 07:57 UTC, merged