Display multiple motds in CLI and deactivate old ones
ScilifelabDataCentre/dds_cli pull request #505
Opened 2022-06-30 13:52 UTC by valyo

Adds ls and deactivate subcommands to `dds motd`
and displaying of multiple active motds

Please include the following in this section

- [ ] Summary of the changes and the related issue
- [ ] Relevant motivation and context
- [ ] Any dependencies that are required for this change

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

Please delete options that are not relevant.

- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Rebase/merge the branch which this PR is made to
- [ ] Product Owner / Scrum Master: This PR is made to the `master` branch and I have updated the [version](../dds_cli/version.py)

## Formatting and documentation

- [ ] I have added a row in the [changelog](../CHANGELOG.md)
- [ ] The code follows the style guidelines of this project: Black / Prettier formatting
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

## Tests

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-07-01 09:31 UTC, inaod568 requested changes
This is to match the suggested change in the web part

2022-07-01 09:31 UTC, inaod568 commented on dds_cli/motd_manager.py
> +                LOG.info("No active Message Of The Day found")
```suggestion
            # Get items from response
            motd = response.get("motds")
            if not motd:
                message = response.get("message")
                if not message:
                    LOG.error("No motds or info message returned from API.")
                
                LOG.info(message)

            motds, keys = dds_cli.utils.get_required_in_response(
                keys=["motds", "keys"], response=response
            )
```

2022-08-04 14:55 UTC, inaod568 commented
@valyo Ok to merge this too? I altered it slightly in the beginning of the week.

2022-08-04 14:57 UTC, valyo commented
> @valyo Ok to merge this too? I altered it slightly in the beginning of the week.

sure, I already saw the changes

2022-08-05 08:39 UTC, inaod568 approved these changes

2022-08-05 08:44 UTC, merged