Command for listing invites
ScilifelabDataCentre/dds_cli pull request #547
Opened 2022-10-06 19:43 UTC by talavis

> **Before submitting the PR, please go through the sections below and fill in what you can. If there are any items that are irrelevant for the current PR, remove the row. If a relevant option is missing, please add it as an item and add a PR comment informing that the new option should be included into this template.**

> **All _relevant_ items should be ticked before the PR is merged**

# Description

Add a command `dds user ls --invites` that will use the new endpoint in #1294 in dds_web.

Implements Jira issue DDS-1354.

- [X] Add a summary of the changes and the related issue
- [ ] Add motivation and context regarding why the change is needed
- [ ] List / describe any dependencies or other changes required for this change
- [X] Fixes [link to issue / Jira issue ID]

## Type of change

- [ ] Documentation
- [ ] Workflow
- [ ] Security Alert fix
- [ ] Bug fix (non-breaking)
- [X] New feature (non-breaking)
- [ ] Breaking change (breaking, will cause existing functionality to not work as expected)
- [ ] Tests (only)

# Checklist:

## General

- [ ] [Changelog](../CHANGELOG.md): New row added. Not needed when PR includes _only_ tests.
- [X] Code change
  - [X] Self-review of code done
  - [ ] Comments added, particularly in hard-to-understand areas
  - [ ] Documentation is updated

## Repository / Releases

- [ ] Blocking PRs have been merged
- [X] Rebase / update of branch done
- [ ] Product Owner / Scrum Master
  - [ ] The [version](../dds_cli/version.py) is updated (PR to `master` branch)
  - [ ] I am bumping the major version (e.g. 1.x.x to 2.x.x)
    - [ ] I have made the corresponding changes to the API version

## Checks

- [X] Formatting: Black & Prettier checks pass
- [ ] CodeQL passes
- [ ] Tests
  - [ ] I have added tests for the new code
  - [ ] The tests pass

2022-10-07 08:08 UTC, inaod568 requested changes
Looks good and works as expected but I think there should be a new `list_invites` function instead of adding the if statement to the existing function.

2022-10-07 08:08 UTC, inaod568 commented on dds_cli/account_manager.py
> +    def list_users(self, unit: str = None, invites: bool = None) -> None:
I think this should be split up into two different funcions: 
```
def list_users(self, unit: str = None) -> None:
```
and 
```
def list_invites(self) -> None:
```

2022-10-07 08:08 UTC, inaod568 commented on dds_cli/__main__.py
> +            lister.list_users(unit=unit, invites=invites)
```suggestion
            if invites:
                lister.list_users(unit=unit)
            else: 
                lister.list_invites()
```

2022-10-10 08:05 UTC, inaod568 approved these changes
Looks good and works as planned - ready to merge after https://github.com/ScilifelabDataCentre/dds_web/pull/1294

2022-10-10 11:12 UTC, valyo approved these changes
Looks fine and works

2022-10-10 11:12 UTC, merged