Add --all flag for listing all projects, active and inactive
ScilifelabDataCentre/dds_cli pull request #556
Opened 2022-10-13 13:44 UTC by valyo

> **Before submitting the PR, please go through the sections below and fill in what you can. If there are any items that are irrelevant for the current PR, remove the row. If a relevant option is missing, please add it as an item and add a PR comment informing that the new option should be included into this template.**

> **All _relevant_ items should be ticked before the PR is merged**

Currently Deleted and Archived projects are included when running dds ls or  dds project ls 
Here we limit it to only including the active ones and adding a flag called --all to indicate that the dds should list all of them.

- [ ] Add a summary of the changes and the related issue
- [ ] Add motivation and context regarding why the change is needed
- [ ] List / describe any dependencies or other changes required for this change
- [ ] Fixes DDS-1306

## Type of change

- [ ] Documentation
- [ ] Workflow
- [ ] Security Alert fix
- [ ] Bug fix (non-breaking)
- [ ] New feature (non-breaking)
- [ ] Breaking change (breaking, will cause existing functionality to not work as expected)
- [ ] Tests (only)

# Checklist:

## General

- [ ] [Changelog](../CHANGELOG.md): New row added. Not needed when PR includes _only_ tests.
- [ ] Code change
  - [ ] Self-review of code done
  - [ ] Comments added, particularly in hard-to-understand areas
  - [ ] Documentation is updated

## Repository / Releases

- [ ] Blocking PRs have been merged
- [ ] Rebase / update of branch done
- [ ] Product Owner / Scrum Master
  - [ ] The [version](../dds_cli/version.py) is updated (PR to `master` branch)
  - [ ] I am bumping the major version (e.g. 1.x.x to 2.x.x)
    - [ ] I have made the corresponding changes to the API version

## Checks

- [ ] Formatting: Black & Prettier checks pass
- [ ] CodeQL passes
- [ ] Tests
  - [ ] I have added tests for the new code
  - [ ] The tests pass

2022-10-13 14:04 UTC, inaod568 commented
Accidentally wrote this comment in the API PR but: https://github.com/ScilifelabDataCentre/dds_web/pull/1302#discussion_r994687329

2022-10-13 15:14 UTC, inaod568 requested changes

2022-10-13 15:14 UTC, inaod568 commented on dds_cli/__main__.py
> +@click.option("--all", is_flag=True, help="List all project connected to your account.")
Maybe this instead to not override the builtin `all`? 
```suggestion
@click.option("--include-inactive", is_flag=True, help="List all project connected to your account.")
```
or 
```suggestion
@click.option("--show-all", is_flag=True, help="List all project connected to your account.")
```

2022-10-13 15:14 UTC, inaod568 commented on dds_cli/__main__.py
> +@click.option("--all", is_flag=True, help="List all project connected to your account.")
Same here

2022-10-13 15:14 UTC, inaod568 commented on dds_cli/data_lister.py
> +            project_info = [p for p in project_info if p["Is Active"]]
Remove this
```suggestion
```
and add this to the method name etc
```
def list_projects(self, sort_by="Updated", <new option name here>: bool = False):
```
and then 
```
        response, _ = dds_cli.utils.perform_request(
            # ... stuff here
            json={"usage": self.show_usage, "get_all or <new option name>": <new option name here>},
            # ... rest of stuff here
        )
```

2022-10-13 15:14 UTC, inaod568 commented on dds_cli/data_lister.py
> +        all: bool = False,
```suggestion
```

2022-10-13 15:14 UTC, inaod568 commented on dds_cli/data_lister.py
> +        self.all = all
```suggestion
```

2022-10-14 07:28 UTC, inaod568 requested changes

2022-10-14 07:28 UTC, inaod568 commented on dds_cli/__main__.py
> +@click.option("--show-all", is_flag=True, help="List all project connected to your account.")
```suggestion
@click.option("--show-all", is_flag=True, help="List all projects connected to your account (including inactive).")
```

2022-10-14 07:28 UTC, inaod568 commented on dds_cli/__main__.py
> +@click.option("--show-all", is_flag=True, help="List all project connected to your account.")
```suggestion
@click.option("--show-all", is_flag=True, help="List all projects connected to your account (including inactive).")
```

2022-10-14 07:28 UTC, inaod568 commented on dds_cli/data_lister.py
> +            json={"usage": self.show_usage, "show_all": self.show_all},
```suggestion
            json={"usage": self.show_usage, "show_all": show_all},
```

2022-10-14 07:28 UTC, inaod568 commented on dds_cli/data_lister.py
> +        self.show_all = show_all
```suggestion
```

2022-10-14 07:28 UTC, inaod568 commented on dds_cli/data_lister.py
> +        show_all: bool = False,
```suggestion
```

2022-10-14 07:28 UTC, inaod568 commented on dds_cli/__main__.py
> +                show_all=show_all,
Move this so that it says `projects = lister.list_projects(sort_by=sort, show_all=show_all)` instead
```suggestion
```

2022-10-19 09:41 UTC, inaod568 requested changes
Looks good! Just remove the commented out mentions of the `show_all`

2022-10-19 09:41 UTC, inaod568 commented on dds_cli/__main__.py
> +                # show_all=show_all,
```suggestion
```

2022-10-19 09:41 UTC, inaod568 commented on dds_cli/data_lister.py
> +        # show_all: bool = False,
```suggestion
```

2022-10-19 09:42 UTC, inaod568 commented
@valyo Also rebase / merge dev into this branch

2022-10-19 09:47 UTC, valyo commented
of course

2022-10-19 10:15 UTC, inaod568 approved these changes
Looks good and works as expected!

2022-10-19 10:17 UTC, merged